### PR TITLE
Improve stuff

### PR DESCRIPTION
**Pull request by khrj**
- Fix gitignore
- Use TypeScript
- Improve code for TypeScript
- Add formatter
- Fix todo in README

### CODE REVIEW

**Comment by cjdenio** [comment]
For ease of scalability, could the `.ts` files all be moved to the `src/` directory? Then add `dist/` to the `.gitignore`

**Comment by cjdenio** [comment]
And maybe use Prettier instead, because it's installable via npm? It's up to you

**Comment by khrj** [comment]
Oh yeah I think prettier is a better idea, I'm just used to pulling in .dprintrc.json because of Deno

**Comment by zfogg** [comment]
lgtm

**Pull request merged**
